services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: dipeshbhojwani
      POSTGRES_PASSWORD: dipu@1681256441
      POSTGRES_DB: ngfood
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  backend:
    image: ngfoods-backend:latest
    container_name: ngfoods_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ngfood
      SPRING_DATASOURCE_USERNAME: dipeshbhojwani
      SPRING_DATASOURCE_PASSWORD: dipu@1681256441
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: ngfoods-frontend:latest
    container_name: ngfoods_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data: