CREATE SCHEMA IF NOT EXISTS ngfood;

CREATE TABLE IF NOT EXISTS ngfood.brokerage_details
(
    id bigint NOT NULL,
    consumer_brokerage_type character varying(255) COLLATE pg_catalog."default",
    create_date timestamp(6) without time zone,
    mill_brokerage_type character varying(255) COLLATE pg_catalog."default",
    order_id bigint,
    mill_brokerage double precision,
    consumer_brokerage double precision,
    CONSTRAINT brokerage_details_pkey PRIMARY KEY (id),
    CONSTRAINT unique_id UNIQUE (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS ngfood.brokerage_details
    OWNER to dipeshbhojwani;

    ------------------------PERSON-----------------------------------
    -- Table: ngfood.person

    -- DROP TABLE IF EXISTS ngfood.person;

    CREATE TABLE IF NOT EXISTS ngfood.person
    (
        person_id bigint NOT NULL,
        name character varying(255) COLLATE pg_catalog."default",
        create_date timestamp(6) without time zone,
        update_date date,
        mob_number character varying(255) COLLATE pg_catalog."default",
        address character varying(255) COLLATE pg_catalog."default",
        city character varying(255) COLLATE pg_catalog."default",
        state character varying(255) COLLATE pg_catalog."default",
        country character varying(255) COLLATE pg_catalog."default",
        CONSTRAINT "PERSON_PK" PRIMARY KEY (person_id),
        CONSTRAINT person_unique_id UNIQUE (person_id)
    )

    TABLESPACE pg_default;

    ALTER TABLE IF EXISTS ngfood.person
        OWNER to dipeshbhojwani;

------------------CONSUMER-------------------------------------
CREATE TABLE IF NOT EXISTS ngfood.consumer
(
    name character varying(255) COLLATE pg_catalog."default",
    consumer_id bigint NOT NULL,
    create_date timestamp(6) without time zone,
    update_date timestamp(6) without time zone,
    gst character varying(255) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    owner bigint,
    contact_person bigint,
    CONSTRAINT "CONSUMER_PK" PRIMARY KEY (consumer_id),
    CONSTRAINT "CONSUMER_PERSON_FK" FOREIGN KEY (owner)
        REFERENCES ngfood.person (person_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT consumer_contact_person_fkey FOREIGN KEY (contact_person)
        REFERENCES ngfood.person (person_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS ngfood.consumer
    OWNER to dipeshbhojwani;

COMMENT ON TABLE ngfood.consumer
    IS 'This table will be used to store the customer details';



-------------------------MILL---------------------------------
-- Table: ngfood.mill

-- DROP TABLE IF EXISTS ngfood.mill;

CREATE TABLE IF NOT EXISTS ngfood.mill
(
    mill_id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    create_date timestamp(6) without time zone,
    update_date timestamp(6) without time zone,
    address character varying(255) COLLATE pg_catalog."default",
    owner bigint,
    type character varying(255) COLLATE pg_catalog."default",
    contact_person bigint,
    gst character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "MILL_PK" PRIMARY KEY (mill_id),
    CONSTRAINT "MILL_PERSON_FK" FOREIGN KEY (owner)
        REFERENCES ngfood.person (person_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT mill_contact_person_fkey FOREIGN KEY (contact_person)
        REFERENCES ngfood.person (person_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS ngfood.mill
    OWNER to dipeshbhojwani;

COMMENT ON TABLE ngfood.mill
    IS 'This thable will contain the information for mills details.';

COMMENT ON COLUMN ngfood.mill.mill_id
    IS 'It is a unique id corresponding to mill.';

---------------------ORDER DETAILS-----------------------------
-- Table: ngfood.order_details

-- DROP TABLE IF EXISTS ngfood.order_details;

CREATE TABLE IF NOT EXISTS ngfood.order_details
(
    order_details_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    bag_weight bigint,
    bill_due_date timestamp(6) without time zone,
    cash_discount double precision,
    no_of_bags bigint,
    order_date date,
    rate bigint,
    remarks character varying(255) COLLATE pg_catalog."default",
    total_amount double precision,
    total_quantity double precision,
    CONSTRAINT order_pkey PRIMARY KEY (order_details_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS ngfood.order_details
    OWNER to dipeshbhojwani;


----------------------------ORDERS---------------------------------
-- Table: ngfood.orders

-- DROP TABLE IF EXISTS ngfood.orders;

CREATE TABLE IF NOT EXISTS ngfood.orders
(
    order_id bigint NOT NULL,
    mill_id bigint NOT NULL,
    consumer_id bigint NOT NULL,
    create_date date,
    order_details_id bigint,
    brokerage_details_id bigint,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id),
    CONSTRAINT uk8hoie7ip7i0wwosttq8lwwdym UNIQUE (brokerage_details_id),
    CONSTRAINT fk18up738eyx1ppn73qgvl5pdmv FOREIGN KEY (order_details_id)
        REFERENCES ngfood.order_details (order_details_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk460lufjj87y4cmv83pclflc8m FOREIGN KEY (brokerage_details_id)
        REFERENCES ngfood.brokerage_details (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS ngfood.orders
    OWNER to dipeshbhojwani;


